### ISSUE TITLE
feat: 협업 방식 정립

### ISSUE THREAD

**Issue by username1103** [username1103/snack-talk#3]
# 깃헙 사용 방법

## Issue

1. 버그 리포트 - Bug Report Template
2. 기능 추가 및 수정 계획 작성 - Feature Template

각각의 템플릿을 선택하여 작성함

## Pull requests

1. 이슈에 있는 항목 중 할일을 선택해 풀리퀘스트 먼저 생성 (프로젝트 In Progree로 변경 위함)
2. 수정사항 모두 수정 후 리뷰?!
3. 머지

## Discussions

1. 도움이나 궁금한거 있으면 작성하여 사용. 간단한건 그냥 카톡. 문서로 남는게 좋으면 discussion이용 (혹시 이거 알아요?)
2. 있었으면 하는 기능 또는 필요한 요구사항 토론 (이거 어때요?)

## Projects

1. 하나씩 프로젝트 단위로 쪼개서 프로젝트 완료후 다음 프로젝트 주제 선정 및 진행
2. 마일스톤 주단위 설정? 또는 프로젝트 내부 세부 프로젝트 별 설정?

## Branch

1. 브랜치 네이밍 컨벤션 및 진행방식 정하기

## 기타

1. 추가적인 레이블 설정

기타 하고 싶은 것 추가하고 싶은 것 수정하고 싶은 것

_Originally posted by @username1103 in https://github.com/username1103/toy-project/discussions/2_

**Comment by username1103** [comment]
- server 과 client 브랜치를 우선 나누고 프로젝트 단위로 master에 머지하기.
- slack으로 대화
- 브랜치 네이밍 : ${issueNumber}-${eat|fix|test|docs|refactor|design}/${comment}
- 커밋네이밍 : [type]: [#issueNumber-]제목\n[body]

**Comment by dadakim-dev** [comment]
@username1103 

- 이번 주 프로젝트 및 마일스톤 선정
  - Slack 채널 개설 후 논의
- 이슈 테스트 추가
- dev 브랜치로 merge하기 위한 로컬 feature 브랜치 **(이하 서브브랜치)** 커밋 convention
  - 좋은 방법인 것 같아요 !
  - 위 예시대로 Resolves, Ref, Related to 에 첨부되는 이슈 넘버는 에디터 Git extension이라던가, 특정 기능을 이용해서 자동으로 첨부되게 할 수 있는 방법이 있나요? (혹시나 해서!)

**Comment by username1103** [comment]
@dadakim-dev 

- 이슈 테스트 추가
  - 이거 왜적었는지 모르겠어용

>   * 위 예시대로 Resolves, Ref, Related to 에 첨부되는 이슈 넘버는 에디터 Git extension이라던가, 특정 기능을 이용해서 자동으로 첨부되게 할 수 있는 방법이 있나요? (혹시나 해서!)
- git hook이란게 있는데, husky사용하면 편하게 git hook을 쓸 수 있어요. 커밋이나 푸쉬등 할 때, 자동 테스트나 린팅 이나 스크립트 작성해서 동작하게 할 수 있어요! 메시지 포맷팅도 가능해요!
