### ISSUE TITLE
docs: DB설계

### ISSUE THREAD

**Issue by username1103** [username1103/snack-talk#7]
# 데이터베이스 설계

## 요구사항

1. 사용자는 채팅방 생성이 가능하다.
1. 사용자는 여러 채팅방을 가지며 조회가능하다.
2. 채팅내용은 저장되어야 한다.
3. 휴대폰번호 + 인증번호를 통해 로그인한다. (인증번호 발급처럼하지만 마스터키로 우선 제작한다)

## 데이터베이스 설계

<img width="902" alt="image" src="https://user-images.githubusercontent.com/67570061/174276685-4ed175b4-77f5-4736-ab2f-5b1f62cd46ff.png">

- UserProfile은 일단 넣어두었는데 채팅 만든 이후에 추가해도 좋을 것 같아요.
- Token은 리프레시 토큰을 저장해두기 위해서 만들었어요. 리프레시 토큰마다 한번만 사용되도록 하기 위해서입니다.
- Room은 글로벌한 채팅방 정보를 담고 있고, UserRoom은 Room과 User의 릴레이션 테이블인데, 사용자별 커스텀할 수 있는 데이터(ex. 카카오톡채팅방 이름)를 담을 수 있도록 하면 좋을 것 같아요.
- Message는 메시지 정보를 담고 있는 테이블로 만들었어요. status는 메시지의 전송상태라고 생각했습니다.(ex. 발송대기, 발송완료) 우선은 디비에 저장후, 메시지큐(ex. redis, rabbitMQ ..)로 메시지를 전달하고 이후에 발송완료 처리되는 것으로 생각하고 추가해두었어요.

---

## 추가사항

아직 이벤트 브로커, 메시지 브로커에 대해 자세하게 알아보지 못해서 좀 더 알아보고 나서 메시지 테이블이 수정될 수 있을 것 같아요.

**Comment by username1103** [comment]
@dadakim-dev 확인부탁드려요

**Comment by dadakim-dev** [comment]
@username1103 확인했습니다! 메시지 같은 경우 혹시 다른 성격의 DB를 사용한다던가 (insert에 특화된) 그럴 계획이 있으신가요~?!

만일 메시지 전송 시 매번 insert가 실행된다면 터질 수도 있겠다는 걱정이 살짝 들어서요...!!

일정 시간이나 컨텐츠의 사이즈를 기준으로 모았다가 데이터를 저장하는 방식도 저장공간이 비워지는 순간에 엄청난 타이밍으로 인한 데이터의 손실이 발생할 가능성도 있지 않을까 생각됩니다 😯

제가 잘 아는 내용이 아닌지라 혹시 어떤 아이디어가 있으신가 궁금해서 여쭤보았어요!!!!

**Comment by username1103** [comment]
@dadakim-dev 우선은 mysql사용해서 기능 구현을 1차 목표로 생각했어요. socket이나 메시지큐같은 부분들도 처음이다보니 ㅠㅠ. 일단은 기능구현이후에 추가사항으로 db관련해서도 수정해보면 좋을 것 같네요.
